"""Citation helpers for answers generated by the local RAG pipeline."""

from __future__ import annotations

import re


CITATION_PATTERN = re.compile(r"\[(\d+)\]")


def extract_citation_ids(answer: str) -> set[int]:
    return {int(match.group(1)) for match in CITATION_PATTERN.finditer(answer)}
